{
 "title": "Order Dashboard",
 "time": { "from": "2015-12-31T18:30:00.000Z", "to": "2016-12-31T18:29:59.000Z" },
 "panels": [
  {
   "title": "Top10 sales",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "salesman.name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "total_amount", "id": "1", "type": "sum" }
     ],
     "timeField": "purchased_at"
    }
   ]
  },
  {
   "title": "TotalSales by Channel",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "sales_channel.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "lines.amount", "id": "1", "type": "sum" }
     ],
     "timeField": "purchased_at"
    },
    { "expression": "$TotalSales > 25000", "reducer": "sum", "settings": { "mode": "" }, "type": "math" }
   ]
  },
  {
   "title": "Order Panel",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 5, "y": 8 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "purchased_at"
    }
   ]
  }
 ]
}